export const FETCH_COLUMN_NAMES = 'FETCH_COLUMN_NAMES';
export const FETCH_COLUMN_NAMES_SUCCESS = 'FETCH_COLUMN_NAMES_SUCCESS';
export const FETCH_COLUMN_NAMES_FAILURE = 'FETCH_COLUMN_NAMES_FAILURE';

export const FETCH_COLUMN_DATA = 'FETCH_COLUMN_DATA';
export const FETCH_COLUMN_DATA_SUCCESS = 'FETCH_COLUMN_DATA_SUCCESS';
export const FETCH_COLUMN_DATA_FAILURE = 'FETCH_COLUMN_DATA_FAILURE';
